[package]
name = "rust_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
# ethers v2.x with WebSocket support
ethers = { version = "2.0", features = ["ws"] }         

# Tokio async runtime with full feature set (macros, time, rt)
tokio  = { version = "1", features = ["full"] }          

# Load environment variables from .env
dotenv = "0.15.0"                                        
